sudo: false
language: python
cache: pip
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION="Django>=1.6,<1.7"
  - DJANGO_VERSION="Django>=1.7,<1.8"
  - DJANGO_VERSION="Django>=1.8,<1.9"
  - DJANGO_VERSION="Django>=1.9,<1.10"
  - DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
matrix:
  exclude:
    # Django >= 1.7 does not support Python 2.6
    - python: "2.6"
      env: DJANGO_VERSION="Django>=1.7,<1.8"
    - python: "2.6"
      env: DJANGO_VERSION="Django>=1.8,<1.9"
    - python: "2.6"
      env: DJANGO_VERSION="Django>=1.9,<1.10"
    - python: "2.6"
      env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
    # Django < 1.8 does not support Python 3.5
    - python: "3.5"
      env: DJANGO_VERSION="Django>=1.6,<1.7"
    - python: "3.5"
      env: DJANGO_VERSION="Django>=1.7,<1.8"
  allow_failures:
     - env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
     - env: DJANGO_VERSION="Django>=1.6,<1.7"
       python: "2.6"
before_install:
  - pip install codecov
install:
  - pip install -q "$DJANGO_VERSION"
  - pip install -r example/requirements.txt
  - pip install -q "$DJANGO_VERSION"
script:
  - pip install .
  - coverage run example/manage.py test
after_script:
  - codecov
