sudo: false
language: python
cache: pip
python:
- '2.6'
- '2.7'
- '3.4'
- '3.5'
env:
- PACKAGES="Django>=1.6,<1.7 django-contrib-comments==1.6.2"
- PACKAGES="Django>=1.7,<1.8"
- PACKAGES="Django>=1.8,<1.9"
- PACKAGES="Django>=1.9,<1.10"
- PACKAGES="Django>=1.10,<1.11"
- PACKAGES='https://github.com/django/django/archive/master.tar.gz'
matrix:
  exclude:
  - python: '2.6'
    env: PACKAGES="Django>=1.7,<1.8"
  - python: '2.6'
    env: PACKAGES="Django>=1.8,<1.9"
  - python: '2.6'
    env: PACKAGES="Django>=1.9,<1.10"
  - python: '2.6'
    env: PACKAGES="Django>=1.10,<1.11"
  - python: '2.6'
    env: PACKAGES='https://github.com/django/django/archive/master.tar.gz'
  - python: '3.5'
    env: PACKAGES="Django>=1.6,<1.7 django-contrib-comments==1.6.2"
  - python: '3.5'
    env: PACKAGES="Django>=1.7,<1.8"
  allow_failures:
  - env: PACKAGES='https://github.com/django/django/archive/master.tar.gz'
  - env: PACKAGES="Django>=1.6,<1.7 django-contrib-comments==1.6.2"
    python: '2.6'
before_install:
- pip install codecov
install:
- pip install -U pip wheel
- pip install $PACKAGES mock -e .
script:
- coverage run example/manage.py test
after_success:
- codecov
branches:
  only:
  - master
notifications:
  irc:
    channels:
    - irc.freenode.org#django-fluent
    template:
    - '%{repository}#%{build_number} (%{commit}) %{message}  --  %{build_url}'
    skip_join: true
  email:
    recipients:
    - travis@edoburu.nl
    on_success: never
    on_failure: always
  slack:
    secure: UQYHU07XN2kSAea1wFMMm9OsDJdavodhQsE8oT3SjxdXCbfBe/M1HXE8lbY2sZetWNiyQrZfodICDxhquQsNnUQ9IwMiSkWyofdT7rFA/2txPtf8bCnVMb0j0qJL+eKhFLBdtAEhi3PmuD2DqxcQxyz81enwtCk3vq8hzBEZu4I=
    on_success: never
    on_failure: always
